@startuml
autonumber
hide footbox
title NSM Local Xconnect Setup
participant nsc as NSC order 10
participant "nsmgr" as LN order 20
participant "forwarder" as LF order 30
participant nse as NSE order 40


NSC->LN: Service.Request
LN->LF: Service.Request
note over LF: callout\nmechanism
LF->LN: Service.Request
LN->NSE: Service.Request
note over NSE: IPAM
NSE->LN: Connection
LN->LF: Connection
note over LF: callout\nrequest
LF-->NSE: Inject-interface
LF-->NSC: Inject-interface
LF->LN: Connection
LN->NSC: Connection

@enduml
